class Property {
  id: string;
  idCompany: string;
  avatarCompany: string;
  fantasyName: string;
  title: string;
  road: string;
  district: string;
  city: string;
  uf: string;
  description: string;
  type: string;
  subType: string;
  status: string;
  newProperty: string;
  firstLease: string;
  availability: string;
  bedroom: string;
  garage: string;
  suite: string;
  restroom: string;
  furnished: string;
  pets: string;
  priceSale: string;
  priceRent: string;
  textRent: string;
  condominium: string;
  iptu: string;
  otherPrices: string;
  yearOfConstruction: string;
  buildingArea: string;
  siglaBuildingArea: string;
  totalArea: string;
  siglaTotalArea: string;
  images: object;
  featuredImage: string;
  platformVideo: string;
  video: string;
  slider: string;
  financing: string;
  characteristcs: object;
  created_at: Date;
}

export { Property };
